### ISSUE TITLE
:)

### ISSUE THREAD

**Issue by KimDarren** [Feghal/ImageDetect#1]
Thanks to copy my source code. 
[FaceCropper.swift](https://github.com/KimDarren/FaceCropper/blob/master/FaceCropper/Classes/FaceCropper.swift)

[ImageDetect.swift](https://github.com/Feghal/ImageDetect/blob/master/ImageDetect/Classes/ImageDetect.swift)

Do your own thing, **COPYCAT** bro 👍

**Comment by Feghal** [comment]
I looked at your code nothing coped just used same mechanism, thanks
